/**
 * Import Browser Fetch Results:
 * 1. Read the CSV generated by the browser tool.
 * 2. For each row, normalize the URL to get the hash.
 * 3. Save content to data/fetched_content/<hash>.txt
 * 4. Save metadata to data/fetched_content/<hash>.json
 */

import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { parse } from 'csv-parse/sync';

const CONFIG = {
    csvPath: 'datapass/url_content_2026-01-31-04-26-20.csv',
    outDir: 'data/fetched_content',
    logPath: 'data/fetch_results_browser_import.jsonl'
};

function shortHash(text) {
    return crypto.createHash('sha256').update(text, 'utf8').digest('hex').slice(0, 16);
}

function normalizeUrlKey(rawUrl) {
    if (!rawUrl) return "";
    let url = rawUrl.trim();
    if (!url.includes("://")) url = `https://${url}`;
    try {
        const p = new URL(url);
        let host = (p.hostname || "").toLowerCase();
        if (host.startsWith("www.")) host = host.slice(4);
        let pathname = p.pathname || "/";
        if (pathname.length > 1 && pathname.endsWith("/")) pathname = pathname.slice(0, -1);
        const dropExact = new Set(["gclid", "fbclid", "msclkid", "yclid", "mc_cid", "mc_eid", "igshid"]);
        const kept = [];
        for (const [k, v] of p.searchParams.entries()) {
            const lk = k.toLowerCase();
            if (lk.startsWith("utm_") || dropExact.has(lk)) continue;
            kept.push([k, v]);
        }
        const q = new URLSearchParams(kept).toString();
        return `${host}${pathname}${q ? `?${q}` : ""}`;
    } catch {
        return rawUrl.toLowerCase();
    }
}

async function main() {
    console.log(`Importing browser fetch results from ${CONFIG.csvPath}...`);
    
    if (!fs.existsSync(CONFIG.csvPath)) {
        console.error("CSV file not found.");
        return;
    }

    if (!fs.existsSync(CONFIG.outDir)) {
        fs.mkdirSync(CONFIG.outDir, { recursive: true });
    }

    const fileContent = fs.readFileSync(CONFIG.csvPath, 'utf8');
    const records = parse(fileContent, {
        columns: true,
        skip_empty_lines: true,
        relax_column_count: true
    });

    let imported = 0;
    let skipped = 0;

    for (const row of records) {
        const url = row.url;
        if (!url) continue;

        const key = normalizeUrlKey(url);
        const hash = shortHash(key);
        const txtPath = path.join(CONFIG.outDir, `${hash}.txt`);
        const jsonPath = path.join(CONFIG.outDir, `${hash}.json`);

        const content = row.content || "";
        if (!content || content.length < 100) {
            skipped++;
            continue;
        }

        // Save .txt
        fs.writeFileSync(txtPath, content);

        // Save .json metadata
        const metadata = {
            url,
            normalized_url: key,
            hash,
            fetched_at: new Date().toISOString(),
            status: parseInt(row.status) || 200,
            ok: true,
            page_title: row.page_title,
            meta_description: row.meta_description,
            canonical_url: row.canonical_url,
            published_date: row.published_date,
            modified_date: row.modified_date,
            has_schema_markup: parseInt(row.has_schema_markup) || 0,
            js_render_suspected: parseInt(row.js_render_suspected) || 0,
            source: "browser_fetcher"
        };
        fs.writeFileSync(jsonPath, JSON.stringify(metadata, null, 2));

        // Log to jsonl
        fs.appendFileSync(CONFIG.logPath, JSON.stringify({ url, hash, ok: true, source: "browser_import" }) + "\n");
        
        imported++;
    }

    console.log(`Import complete!`);
    console.log(`Imported: ${imported}`);
    console.log(`Skipped (no content): ${skipped}`);
}

main().catch(console.error);
